### ISSUE TITLE
泳ぐオブジェクトの尻尾がワープする問題について

### ISSUE THREAD

**Issue by smilenannan** [smilenannan/brainwave1#6]
先頭を泳ぐオブジェクトが画面外に出てしまうと、尻尾は追従するため瞬間移動します。
例えば、先頭のオブジェクトが上にはみ出ると下に移るため尻尾の移動ベクトルが大きく下向きになるため、下の方に瞬間移動してしまいます。

**Comment by smilenannan** [comment]
一つの解決策として、processingの出力画面をパソコンの画面より大きくし、エッジを見えなくすることです（新しくコードを追加する必要がないので楽ではある）

**Comment by kyanamoti** [comment]
出力画面を大きくした場合画面外にオブジェクトが集まってしまうと可視範囲内にいる個体数が減ってしまう。それを量でカバーしようとするとおそらくPCがかなり重くなるのでやはりアルゴリズムを変えたい所。

**Comment by smilenannan** [comment]
集まっても移動し続けるし、そんな時間とらないんじゃない？

**Comment by kyanamoti** [comment]
画面を個体の大きさ+α分(80くらい?)だけおおきくすればそんなに隠れないしワープもしないのでいいかも。ただ上の辺を隠すためにウィンドウを移動させる必要あり。

**Comment by smilenannan** [comment]
きゃなありがとう！座標を負まで考えればうまく動いた！画面で表示されてる座標っていうのはx,yが正の部分だから、boid, seekobjectのふるまいとして、if(xpos<-100)とかにしたらうまくいった！プッシュするから動作確認してみて！
