### ISSUE TITLE
オブジェクトのデザイン及び発光について

### ISSUE THREAD

**Issue by kyanamoti** [smilenannan/brainwave1#7]
オブジェクトのデザインについていろいろ検討しています。
先日追加したとおりかたまって動くオブジェクトの実装はできたものの、デザインが複雑すぎると量が増えたときの気持ち悪さが増すためできればシンプルにしたい。
また発光表現の適応はかなり見た目が良くなるものの、描けるバリエーションとしては現状円とせいぜい直線。斜め線になるだけでも難易度が上がるため現在試行錯誤中。

**Comment by smilenannan** [comment]
どんな感じになってるか見てみたいからobjectsブランチにプッシュしてくれるとありがたい！
